[workspace]
members = [
    "programs/*"
]
resolvers = ["2"]
exclude = [
    "app",
]

[profile.release]
overflow-checks = true
lto = "thin"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

